In [54]:
import pandas as pd
from bs4 import BeautifulSoup as soup
from bs4 import NavigableString, Tag
import requests
import csv 

years = range(1985,2017) # have a list of years
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
base_url = "https://en.wikipedia.org/wiki"

df = pd.DataFrame()
# iterate over each year's wiki page to build a bag of words of good/bad things that happened
for year in years:
    print('.', end='')
    url = f"{base_url}/{year}"
    response = requests.get(url)
    if response.status_code != 200:
        print(f"GET failed with response code: {response.status_code}")
        raise
        
    year_soup = soup(response.text, 'html5lib')
    uls = year_soup.find_all('ul')
    # iterate over each month
    for month in months:
        # iterate over all the uls in the hardcoded range of desired uls
        for i, ul in enumerate(uls[16:]):
            if month in ul.get_text():
#                 print(f"I ==== {i}", ul.get_text())
                df = df.append({'year': int(year), 'month': month, 'text': ul.get_text().encode('ascii','ignore').decode()}, ignore_index=True)
# #         bullets = [year.get_text() for year in year_soup.find_all('ul')]
#         print(ms)
df

................................

         month                                               text    year
0      January  January 1\nThe Internet's Domain Name System i...  1985.0
1      January  The Internet's Domain Name System is created.\...  1985.0
2      January  January 1\nJeff Carter, Canadian hockey player...  1985.0
3      January  January 2  Gabriel Elorde, Filipino profession...  1985.0
4     February  February 4  The border between Gibraltar and S...  1985.0
...        ...                                                ...     ...
1395  November  November 2  Oleg Popov, Soviet and Russian clo...  2016.0
1396  November  \n\t This page was last edited on 9 November 2...  2016.0
1397  December  September 1  An annular solar eclipse was visi...  2016.0
1398  December  December 19  Andrei Karlov, the Russian ambass...  2016.0
1399  December  December 2  Sammy Lee, American Olympic diver ...  2016.0

[1400 rows x 3 columns]

In [55]:
df_csv = df.to_csv()
with open('Project1_sentiment.csv', 'w') as f:
    f.write(df_csv)

In [112]:
# Alt approach using the "next_element"
from bs4 import NavigableString, Tag


years = range(1985,2017) # have a list of years
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
base_url = "https://en.wikipedia.org/wiki"

df2 = pd.DataFrame()
# iterate over each year's wiki page to build a bag of words of good/bad things that happened
for year in years:
    url = f"{base_url}/{year}"
    response = requests.get(url)
    if response.status_code != 200:
        print(f"GET failed with response code: {response.status_code}")
        raise
        
    year_soup = soup(response.text, 'html5lib')
    for month in months:
        print(f"GETTING {year}-{month}")
        span = year_soup.find('span', {'id': month})
        for elem in span.parent.findNext('ul'):
            if isinstance(elem, NavigableString):
                continue
            elif isinstance(elem, Tag):
#                 print(elem.get_text())
                df2 = df2.append({'year': int(year), 'month': month, 'text': elem.get_text().encode('ascii','ignore').decode()}, ignore_index=True)
df2

GETTING 1985-January
GETTING 1985-February
GETTING 1985-March
GETTING 1985-April
GETTING 1985-May
GETTING 1985-June
GETTING 1985-July
GETTING 1985-August
GETTING 1985-September
GETTING 1985-October
GETTING 1985-November
GETTING 1985-December
GETTING 1986-January
GETTING 1986-February
GETTING 1986-March
GETTING 1986-April
GETTING 1986-May
GETTING 1986-June
GETTING 1986-July
GETTING 1986-August
GETTING 1986-September
GETTING 1986-October
GETTING 1986-November
GETTING 1986-December
GETTING 1987-January
GETTING 1987-February
GETTING 1987-March
GETTING 1987-April
GETTING 1987-May
GETTING 1987-June
GETTING 1987-July
GETTING 1987-August
GETTING 1987-September
GETTING 1987-October
GETTING 1987-November
GETTING 1987-December
GETTING 1988-January
GETTING 1988-February
GETTING 1988-March
GETTING 1988-April
GETTING 1988-May
GETTING 1988-June
GETTING 1988-July
GETTING 1988-August
GETTING 1988-September
GETTING 1988-October
GETTING 1988-November
GETTING 1988-December
GETTING 1989-January
GETTING 1989-February
GETTING 1989-March
GETTING 1989-April
GETTING 1989-May
GETTING 1989-June
GETTING 1989-July
GETTING 1989-August
GETTING 1989-September
GETTING 1989-October
GETTING 1989-November
GETTING 1989-December
GETTING 1990-January
GETTING 1990-February
GETTING 1990-March
GETTING 1990-April
GETTING 1990-May
GETTING 1990-June
GETTING 1990-July
GETTING 1990-August
GETTING 1990-September
GETTING 1990-October
GETTING 1990-November
GETTING 1990-December
GETTING 1991-January
GETTING 1991-February
GETTING 1991-March
GETTING 1991-April
GETTING 1991-May
GETTING 1991-June
GETTING 1991-July
GETTING 1991-August
GETTING 1991-September
GETTING 1991-October
GETTING 1991-November
GETTING 1991-December
GETTING 1992-January
GETTING 1992-February
GETTING 1992-March
GETTING 1992-April
GETTING 1992-May
GETTING 1992-June
GETTING 1992-July
GETTING 1992-August
GETTING 1992-September
GETTING 1992-October
GETTING 1992-November
GETTING 1992-December
GETTING 1993-January
GETTING 1993-February
GETTING 1993-March
GETTING 1993-April
GETTING 1993-May
GETTING 1993-June
GETTING 1993-July
GETTING 1993-August
GETTING 1993-September
GETTING 1993-October
GETTING 1993-November
GETTING 1993-December
GETTING 1994-January
GETTING 1994-February
GETTING 1994-March
GETTING 1994-April
GETTING 1994-May
GETTING 1994-June
GETTING 1994-July
GETTING 1994-August
GETTING 1994-September
GETTING 1994-October
GETTING 1994-November
GETTING 1994-December
GETTING 1995-January
GETTING 1995-February
GETTING 1995-March
GETTING 1995-April
GETTING 1995-May
GETTING 1995-June
GETTING 1995-July
GETTING 1995-August
GETTING 1995-September
GETTING 1995-October
GETTING 1995-November
GETTING 1995-December
GETTING 1996-January
GETTING 1996-February
GETTING 1996-March
GETTING 1996-April
GETTING 1996-May
GETTING 1996-June
GETTING 1996-July
GETTING 1996-August
GETTING 1996-September
GETTING 1996-October
GETTING 1996-November
GETTING 1996-December
GETTING 1997-January
GETTING 1997-February
GETTING 1997-March
GETTING 1997-April
GETTING 1997-May
GETTING 1997-June
GETTING 1997-July
GETTING 1997-August
GETTING 1997-September
GETTING 1997-October
GETTING 1997-November
GETTING 1997-December
GETTING 1998-January
GETTING 1998-February
GETTING 1998-March
GETTING 1998-April
GETTING 1998-May
GETTING 1998-June
GETTING 1998-July
GETTING 1998-August
GETTING 1998-September
GETTING 1998-October
GETTING 1998-November
GETTING 1998-December
GETTING 1999-January
GETTING 1999-February
GETTING 1999-March
GETTING 1999-April
GETTING 1999-May
GETTING 1999-June
GETTING 1999-July
GETTING 1999-August
GETTING 1999-September
GETTING 1999-October
GETTING 1999-November
GETTING 1999-December
GETTING 2000-January
GETTING 2000-February
GETTING 2000-March
GETTING 2000-April
GETTING 2000-May
GETTING 2000-June
GETTING 2000-July
GETTING 2000-August
GETTING 2000-September
GETTING 2000-October
GETTING 2000-November
GETTING 2000-December
GETTING 2001-January
GETTING 2001-February
GETTING 2001-March
GETTING 2001-April
GETTING 2001-May
GETTING 2001-June
GETTING 2001-July
GETTING 2001-August
GETTING 2001-September
GETTING 2001-October
GETTING 2001-November
GETTING 2001-December
GETTING 2002-January
GETTING 2002-February
GETTING 2002-March
GETTING 2002-April
GETTING 2002-May
GETTING 2002-June
GETTING 2002-July
GETTING 2002-August
GETTING 2002-September
GETTING 2002-October
GETTING 2002-November
GETTING 2002-December
GETTING 2003-January
GETTING 2003-February
GETTING 2003-March
GETTING 2003-April
GETTING 2003-May
GETTING 2003-June
GETTING 2003-July
GETTING 2003-August
GETTING 2003-September
GETTING 2003-October
GETTING 2003-November
GETTING 2003-December
GETTING 2004-January
GETTING 2004-February
GETTING 2004-March
GETTING 2004-April
GETTING 2004-May
GETTING 2004-June
GETTING 2004-July
GETTING 2004-August
GETTING 2004-September
GETTING 2004-October
GETTING 2004-November
GETTING 2004-December
GETTING 2005-January
GETTING 2005-February
GETTING 2005-March
GETTING 2005-April
GETTING 2005-May
GETTING 2005-June
GETTING 2005-July
GETTING 2005-August
GETTING 2005-September
GETTING 2005-October
GETTING 2005-November
GETTING 2005-December
GETTING 2006-January
GETTING 2006-February
GETTING 2006-March
GETTING 2006-April
GETTING 2006-May
GETTING 2006-June
GETTING 2006-July
GETTING 2006-August
GETTING 2006-September
GETTING 2006-October
GETTING 2006-November
GETTING 2006-December
GETTING 2007-January
GETTING 2007-February
GETTING 2007-March
GETTING 2007-April
GETTING 2007-May
GETTING 2007-June
GETTING 2007-July
GETTING 2007-August
GETTING 2007-September
GETTING 2007-October
GETTING 2007-November
GETTING 2007-December
GETTING 2008-January
GETTING 2008-February
GETTING 2008-March
GETTING 2008-April
GETTING 2008-May
GETTING 2008-June
GETTING 2008-July
GETTING 2008-August
GETTING 2008-September
GETTING 2008-October
GETTING 2008-November
GETTING 2008-December
GETTING 2009-January
GETTING 2009-February
GETTING 2009-March
GETTING 2009-April
GETTING 2009-May
GETTING 2009-June
GETTING 2009-July
GETTING 2009-August
GETTING 2009-September
GETTING 2009-October
GETTING 2009-November
GETTING 2009-December
GETTING 2010-January
GETTING 2010-February
GETTING 2010-March
GETTING 2010-April
GETTING 2010-May
GETTING 2010-June
GETTING 2010-July
GETTING 2010-August
GETTING 2010-September
GETTING 2010-October
GETTING 2010-November
GETTING 2010-December
GETTING 2011-January
GETTING 2011-February
GETTING 2011-March
GETTING 2011-April
GETTING 2011-May
GETTING 2011-June
GETTING 2011-July
GETTING 2011-August
GETTING 2011-September
GETTING 2011-October
GETTING 2011-November
GETTING 2011-December
GETTING 2012-January
GETTING 2012-February
GETTING 2012-March
GETTING 2012-April
GETTING 2012-May
GETTING 2012-June
GETTING 2012-July
GETTING 2012-August
GETTING 2012-September
GETTING 2012-October
GETTING 2012-November
GETTING 2012-December
GETTING 2013-January
GETTING 2013-February
GETTING 2013-March
GETTING 2013-April
GETTING 2013-May
GETTING 2013-June
GETTING 2013-July
GETTING 2013-August
GETTING 2013-September
GETTING 2013-October
GETTING 2013-November
GETTING 2013-December
GETTING 2014-January
GETTING 2014-February
GETTING 2014-March
GETTING 2014-April
GETTING 2014-May
GETTING 2014-June
GETTING 2014-July
GETTING 2014-August
GETTING 2014-September
GETTING 2014-October
GETTING 2014-November
GETTING 2014-December
GETTING 2015-January
GETTING 2015-February
GETTING 2015-March
GETTING 2015-April
GETTING 2015-May
GETTING 2015-June
GETTING 2015-July
GETTING 2015-August
GETTING 2015-September
GETTING 2015-October
GETTING 2015-November
GETTING 2015-December
GETTING 2016-January
GETTING 2016-February
GETTING 2016-March
GETTING 2016-April
GETTING 2016-May
GETTING 2016-June
GETTING 2016-July
GETTING 2016-August
GETTING 2016-September
GETTING 2016-October
GETTING 2016-November
GETTING 2016-December

         month                                               text    year
0      January  January 1\nThe Internet's Domain Name System i...  1985.0
1      January  January 7  Japan Aerospace Exploration Agency ...  1985.0
2      January  January 10  Sinclair C5, the world's first mas...  1985.0
3      January  January 13  A passenger train plunges into a r...  1985.0
4      January  January 15  Tancredo Neves is elected presiden...  1985.0
...        ...                                                ...     ...
2947  December  December 19  Andrei Karlov, the Russian ambass...  2016.0
2948  December  December 22  A study finds the VSV-EBOV vaccin...  2016.0
2949  December  December 23  The United Nations Security Counc...  2016.0
2950  December  December 25  2016 Russian Defence Ministry Tup...  2016.0
2951  December  December 31  United States troops withdraw fro...  2016.0

[2952 rows x 3 columns]